[package]
name = "example"
description = "example"
version.workspace = true
edition.workspace = true
license = "MIT"
authors = ["Gnosis Guild / Enclave"]

[lib]
name = "example_lib"
path = "src/lib.rs"

[[bin]]
name = "example"
path = "src/main.rs"

[dependencies]
rand = { workspace = true }
